import { UserRole } from "@prisma/client";

export const PERMISSIONS = {
  // Mess
  MESS_CREATE: "mess:create",
  MESS_READ: "mess:read",
  MESS_UPDATE: "mess:update",
  MESS_DELETE: "mess:delete",
  MESS_TRANSFER: "mess:transfer",
  // Members
  MEMBER_INVITE: "member:invite",
  MEMBER_APPROVE: "member:approve",
  MEMBER_BAN: "member:ban",
  MEMBER_SUSPEND: "member:suspend",
  MEMBER_READ: "member:read",
  MEMBER_UPDATE: "member:update",
  // Meals
  MEAL_CREATE: "meal:create",
  MEAL_READ: "meal:read",
  MEAL_UPDATE: "meal:update",
  MEAL_DELETE: "meal:delete",
  // Expenses
  EXPENSE_CREATE: "expense:create",
  EXPENSE_READ: "expense:read",
  EXPENSE_UPDATE: "expense:update",
  EXPENSE_DELETE: "expense:delete",
  EXPENSE_APPROVE: "expense:approve",
  // Bills
  BILL_CREATE: "bill:create",
  BILL_READ: "bill:read",
  BILL_UPDATE: "bill:update",
  BILL_DELETE: "bill:delete",
  BILL_PAYMENT: "bill:payment",
  RECURRING_BILL_MANAGE: "bill:recurring",
  // Deposits
  DEPOSIT_CREATE: "deposit:create",
  DEPOSIT_READ: "deposit:read",
  DEPOSIT_APPROVE: "deposit:approve",
  // Rooms
  ROOM_MANAGE: "room:manage",
  // Reports
  REPORT_VIEW: "report:view",
  REPORT_EXPORT: "report:export",
  // Notices
  NOTICE_CREATE: "notice:create",
  NOTICE_READ: "notice:read",
  // Tasks
  TASK_MANAGE: "task:manage",
  // Visitors
  VISITOR_MANAGE: "visitor:manage",
  // Bazaar
  BAZAAR_MANAGE: "bazaar:manage",
  // AI
  AI_ACCESS: "ai:access",
  // Admin
  ADMIN_ACCESS: "admin:access",
  SUPER_ADMIN: "super_admin:access",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: Object.values(PERMISSIONS).filter((p) => p !== PERMISSIONS.SUPER_ADMIN),
  MESS_OWNER: [
    PERMISSIONS.MESS_READ,
    PERMISSIONS.MESS_UPDATE,
    PERMISSIONS.MESS_DELETE,
    PERMISSIONS.MESS_TRANSFER,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_APPROVE,
    PERMISSIONS.MEMBER_BAN,
    PERMISSIONS.MEMBER_SUSPEND,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_READ,
    PERMISSIONS.MEAL_UPDATE,
    PERMISSIONS.MEAL_DELETE,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_UPDATE,
    PERMISSIONS.EXPENSE_DELETE,
    PERMISSIONS.EXPENSE_APPROVE,
    PERMISSIONS.BILL_CREATE,
    PERMISSIONS.BILL_READ,
    PERMISSIONS.BILL_UPDATE,
    PERMISSIONS.BILL_DELETE,
    PERMISSIONS.BILL_PAYMENT,
    PERMISSIONS.RECURRING_BILL_MANAGE,
    PERMISSIONS.DEPOSIT_CREATE,
    PERMISSIONS.DEPOSIT_READ,
    PERMISSIONS.DEPOSIT_APPROVE,
    PERMISSIONS.ROOM_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.TASK_MANAGE,
    PERMISSIONS.VISITOR_MANAGE,
    PERMISSIONS.BAZAAR_MANAGE,
    PERMISSIONS.AI_ACCESS,
  ],
  MESS_MANAGER: [
    PERMISSIONS.MESS_READ,
    PERMISSIONS.MESS_UPDATE,
    PERMISSIONS.MESS_TRANSFER,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_APPROVE,
    PERMISSIONS.MEMBER_BAN,
    PERMISSIONS.MEMBER_SUSPEND,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_READ,
    PERMISSIONS.MEAL_UPDATE,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_APPROVE,
    PERMISSIONS.BILL_CREATE,
    PERMISSIONS.BILL_READ,
    PERMISSIONS.BILL_UPDATE,
    PERMISSIONS.BILL_DELETE,
    PERMISSIONS.BILL_PAYMENT,
    PERMISSIONS.RECURRING_BILL_MANAGE,
    PERMISSIONS.DEPOSIT_CREATE,
    PERMISSIONS.DEPOSIT_READ,
    PERMISSIONS.DEPOSIT_APPROVE,
    PERMISSIONS.ROOM_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.TASK_MANAGE,
    PERMISSIONS.VISITOR_MANAGE,
    PERMISSIONS.BAZAAR_MANAGE,
  ],
  ASSISTANT_MANAGER: [
    PERMISSIONS.MESS_READ,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_APPROVE,
    PERMISSIONS.MEMBER_BAN,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_READ,
    PERMISSIONS.MEAL_UPDATE,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.BILL_CREATE,
    PERMISSIONS.BILL_READ,
    PERMISSIONS.DEPOSIT_CREATE,
    PERMISSIONS.DEPOSIT_READ,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.TASK_MANAGE,
    PERMISSIONS.VISITOR_MANAGE,
    PERMISSIONS.BAZAAR_MANAGE,
    PERMISSIONS.REPORT_VIEW,
  ],
  ACCOUNTANT: [
    PERMISSIONS.MESS_READ,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEAL_READ,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_UPDATE,
    PERMISSIONS.BILL_CREATE,
    PERMISSIONS.BILL_READ,
    PERMISSIONS.BILL_UPDATE,
    PERMISSIONS.BILL_PAYMENT,
    PERMISSIONS.DEPOSIT_CREATE,
    PERMISSIONS.DEPOSIT_READ,
    PERMISSIONS.DEPOSIT_APPROVE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  MEMBER: [
    PERMISSIONS.MESS_READ,
    PERMISSIONS.MEAL_READ,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.BILL_READ,
    PERMISSIONS.DEPOSIT_READ,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.REPORT_VIEW,
  ],
  GUEST: [PERMISSIONS.MESS_READ, PERMISSIONS.NOTICE_READ],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function hasAnyPermission(role: UserRole, permissions: Permission[]): boolean {
  return permissions.some((p) => hasPermission(role, p));
}

export function canManageMess(role: UserRole): boolean {
  return hasAnyPermission(role, [
    PERMISSIONS.MESS_UPDATE,
    PERMISSIONS.MESS_DELETE,
    PERMISSIONS.MESS_TRANSFER,
  ]);
}

export function isAdminRole(role: UserRole): boolean {
  return role === "SUPER_ADMIN" || role === "ADMIN";
}
