export type ReportLocale = "en" | "bn";

const APP_NAME = { en: "MessFlow Pro", bn: "মেসফ্লো প্রো" };

const META: Record<string, { en: string; bn: string }> = {
  summary: { en: "Executive Summary", bn: "সারাংশ" },
  generatedBy: { en: "Generated By", bn: "প্রস্তুতকারী" },
  generatedAt: { en: "Generated Time", bn: "প্রস্তুতের সময়" },
  generatedOn: { en: "Generated Date", bn: "প্রস্তুতের তারিখ" },
  reportType: { en: "Report Type", bn: "রিপোর্টের ধরন" },
  period: { en: "Period", bn: "সময়কাল" },
  month: { en: "Month", bn: "মাস" },
  year: { en: "Year", bn: "বছর" },
  language: { en: "Language", bn: "ভাষা" },
  noData: { en: "No data for this period.", bn: "এই সময়ের জন্য কোনো ডেটা নেই।" },
  confidential: { en: "Confidential", bn: "গোপনীয়" },
  page: { en: "Page", bn: "পৃষ্ঠা" },
  of: { en: "of", bn: "এর" },
  reportId: { en: "Report ID", bn: "রিপোর্ট আইডি" },
  expenseBreakdown: { en: "Expense Breakdown", bn: "খরচ বিভাজন" },
  dataTable: { en: "Details", bn: "বিস্তারিত" },
  english: { en: "English", bn: "ইংরেজি" },
  bangla: { en: "Bangla", bn: "বাংলা" },
};

export const REPORT_TITLES: Record<string, { en: string; bn: string }> = {
  monthly: { en: "Monthly Settlement Report", bn: "মাসিক হিসাব রিপোর্ট" },
  balance_sheet: { en: "Balance Report", bn: "ব্যালেন্স রিপোর্ট" },
  member: { en: "Member Report", bn: "সদস্য রিপোর্ট" },
  meal: { en: "Meal Report", bn: "মিল রিপোর্ট" },
  expense: { en: "Expense Report", bn: "খরচ রিপোর্ট" },
  deposit: { en: "Deposit Report", bn: "জমা রিপোর্ট" },
  daily: { en: "Daily Report", bn: "দৈনিক রিপোর্ট" },
  weekly: { en: "Weekly Report", bn: "সাপ্তাহিক রিপোর্ট" },
  utility: { en: "Utility Bill Report", bn: "ইউটিলিটি বিল রিপোর্ট" },
  rent: { en: "Rent Report", bn: "ভাড়া রিপোর্ট" },
  shared_expense: { en: "Shared Expense Report", bn: "ভাগীয় খরচ রিপোর্ট" },
  bill_settlement: { en: "Bill Settlement Report", bn: "বিল নিষ্পত্তি রিপোর্ট" },
  due: { en: "Due Report", bn: "বকেয়া রিপোর্ট" },
  bazaar: { en: "Bazaar Report", bn: "বাজার রিপোর্ট" },
  transaction: { en: "Transaction Report", bn: "লেনদেন রিপোর্ট" },
  yearly: { en: "Annual Financial Report", bn: "বার্ষিক আর্থিক রিপোর্ট" },
};

const COLUMNS: Record<string, { en: string; bn: string }> = {
  name: { en: "Member", bn: "সদস্য" },
  role: { en: "Role", bn: "ভূমিকা" },
  meals: { en: "Meals", bn: "মিল" },
  mealCost: { en: "Meal Cost", bn: "মিল খরচ" },
  deposit: { en: "Deposit", bn: "জমা" },
  rent: { en: "Rent Share", bn: "ভাড়া অংশ" },
  utilities: { en: "Utility Share", bn: "ইউটিলিটি অংশ" },
  otherBills: { en: "Other Cost", bn: "অন্যান্য খরচ" },
  totalCost: { en: "Total Cost", bn: "মোট খরচ" },
  balance: { en: "Balance", bn: "ব্যালেন্স" },
  due: { en: "Due", bn: "বকেয়া" },
  advance: { en: "Advance", bn: "অগ্রিম" },
  status: { en: "Status", bn: "অবস্থা" },
  phone: { en: "Phone", bn: "ফোন" },
  date: { en: "Date", bn: "তারিখ" },
  member: { en: "Member", bn: "সদস্য" },
  breakfast: { en: "Breakfast", bn: "সকাল" },
  lunch: { en: "Lunch", bn: "দুপুর" },
  dinner: { en: "Dinner", bn: "রাত" },
  total: { en: "Total", bn: "মোট" },
  category: { en: "Category", bn: "বিভাগ" },
  description: { en: "Description", bn: "বিবরণ" },
  amount: { en: "Amount", bn: "পরিমাণ" },
  method: { en: "Method", bn: "পদ্ধতি" },
  type: { en: "Type", bn: "ধরন" },
  notes: { en: "Notes", bn: "নোট" },
  detail: { en: "Detail", bn: "বিস্তারিত" },
  metric: { en: "Metric", bn: "মেট্রিক" },
  value: { en: "Value", bn: "মান" },
  billShare: { en: "Bill Share", bn: "বিল অংশ" },
  vendor: { en: "Vendor", bn: "বিক্রেতা" },
  month: { en: "Month", bn: "মাস" },
  dueDate: { en: "Due Date", bn: "শেষ তারিখ" },
};

const SUMMARY: Record<string, { en: string; bn: string }> = {
  totalMembers: { en: "Total Members", bn: "মোট সদস্য" },
  activeMembers: { en: "Active Members", bn: "সক্রিয় সদস্য" },
  totalDeposits: { en: "Total Deposits", bn: "মোট জমা" },
  totalExpenses: { en: "Total Expenses", bn: "মোট খরচ" },
  totalMeals: { en: "Total Meals", bn: "মোট মিল" },
  mealRate: { en: "Meal Rate", bn: "মিল রেট" },
  totalUtilityBills: { en: "Utility Total", bn: "ইউটিলিটি মোট" },
  totalRent: { en: "Rent", bn: "ভাড়া" },
  totalSharedCost: { en: "Shared Cost", bn: "ভাগীয় খরচ" },
  totalDue: { en: "Total Due", bn: "মোট বকেয়া" },
  totalAdvance: { en: "Total Advance", bn: "মোট অগ্রিম" },
  closingBalance: { en: "Closing Balance", bn: "সমাপনী ব্যালেন্স" },
  members: { en: "Members", bn: "সদস্য" },
  entries: { en: "Entries", bn: "এন্ট্রি" },
  billCount: { en: "Bill Count", bn: "বিল সংখ্যা" },
  totalAmount: { en: "Total Amount", bn: "মোট পরিমাণ" },
  totalBills: { en: "Total Bills", bn: "মোট বিল" },
  membersWithDue: { en: "Members With Due", bn: "বকেয়া সদস্য" },
  highestDue: { en: "Highest Due", bn: "সর্বোচ্চ বকেয়া" },
  collectionRate: { en: "Collection Rate", bn: "আদায়ের হার" },
  totalBazaarCost: { en: "Total Bazaar Cost", bn: "মোট বাজার খরচ" },
  transactions: { en: "Transactions", bn: "লেনদেন" },
  totalCredit: { en: "Total Credit", bn: "মোট জমা (ক্রেডিট)" },
  totalDebit: { en: "Total Debit", bn: "মোট খরচ (ডেবিট)" },
  year: { en: "Year", bn: "বছর" },
  months: { en: "Months", bn: "মাস সংখ্যা" },
  period: { en: "Period", bn: "সময়কাল" },
  net: { en: "Net", bn: "নিট" },
  expenses: { en: "Expenses", bn: "খরচ" },
  deposits: { en: "Deposits", bn: "জমা" },
  date: { en: "Date", bn: "তারিখ" },
};

const SUMMARY_LABEL_TO_KEY: Record<string, string> = {
  "Total Members": "totalMembers",
  "Active Members": "activeMembers",
  "Total Deposits": "totalDeposits",
  "Total Expenses": "totalExpenses",
  "Total Meals": "totalMeals",
  "Meal Rate": "mealRate",
  "Total Utility Bills": "totalUtilityBills",
  "Total Rent": "totalRent",
  "Total Shared Cost": "totalSharedCost",
  "Total Due": "totalDue",
  "Total Advance": "totalAdvance",
  "Closing Balance": "closingBalance",
  Members: "members",
  Entries: "entries",
  Date: "date",
  Meals: "totalMeals",
  Expenses: "expenses",
  Deposits: "deposits",
  Period: "period",
  Net: "net",
  "Bill Count": "billCount",
  "Total Amount": "totalAmount",
  "Total Bills": "totalBills",
  "Members With Due": "membersWithDue",
  "Highest Due": "highestDue",
  "Collection Rate": "collectionRate",
  "Total Bazaar Cost": "totalBazaarCost",
  Transactions: "transactions",
  "Total Credit": "totalCredit",
  "Total Debit": "totalDebit",
  Year: "year",
  Months: "months",
  Electricity: "electricity",
  Water: "water",
  Gas: "gas",
  Internet: "internet",
};

const STATUS: Record<string, { en: string; bn: string }> = {
  Due: { en: "Due", bn: "বকেয়া" },
  Clear: { en: "Clear", bn: "পরিষ্কার" },
  Advance: { en: "Advance", bn: "অগ্রিম" },
  ACTIVE: { en: "Active", bn: "সক্রিয়" },
  CLOSED: { en: "Closed", bn: "বন্ধ" },
  ARCHIVED: { en: "Archived", bn: "সংরক্ষিত" },
  PENDING: { en: "Pending", bn: "অপেক্ষমাণ" },
  PAID: { en: "Paid", bn: "পরিশোধিত" },
  OVERDUE: { en: "Overdue", bn: "মেয়াদোত্তীর্ণ" },
  ASSIGNED: { en: "Assigned", bn: "নির্ধারিত" },
  IN_PROGRESS: { en: "In Progress", bn: "চলমান" },
  PENDING_REVIEW: { en: "Pending Review", bn: "পর্যালোচনাধীন" },
  APPROVED: { en: "Approved", bn: "অনুমোদিত" },
  REJECTED: { en: "Rejected", bn: "প্রত্যাখ্যাত" },
  CORRECTION_REQUESTED: { en: "Correction Needed", bn: "সংশোধন প্রয়োজন" },
  CANCELLED: { en: "Cancelled", bn: "বাতিল" },
  Meal: { en: "Meal", bn: "মিল" },
  Expense: { en: "Expense", bn: "খরচ" },
  Deposit: { en: "Deposit", bn: "জমা" },
  CREDIT: { en: "Credit", bn: "জমা" },
  DEBIT: { en: "Debit", bn: "খরচ" },
};

const ROLES: Record<string, { en: string; bn: string }> = {
  MEMBER: { en: "Member", bn: "সদস্য" },
  MESS_MANAGER: { en: "Manager", bn: "ম্যানেজার" },
  MESS_OWNER: { en: "Owner", bn: "মালিক" },
  ASSISTANT_MANAGER: { en: "Assistant Manager", bn: "সহকারী ম্যানেজার" },
  ACCOUNTANT: { en: "Accountant", bn: "হিসাবরক্ষক" },
};

function pick(dict: Record<string, { en: string; bn: string }>, key: string, locale: ReportLocale): string {
  const entry = dict[key];
  if (entry) return locale === "bn" ? entry.bn : entry.en;
  return key;
}

export function reportLabel(key: string, locale: string): string {
  return pick(META, key, locale as ReportLocale) ?? key;
}

export function reportTitle(type: string, locale: string): string {
  return pick(REPORT_TITLES, type, locale as ReportLocale) ?? type;
}

export function columnLabel(key: string, locale: string): string {
  return pick(COLUMNS, key, locale as ReportLocale) ?? key;
}

export function summaryLabel(key: string, locale: string): string {
  return pick(SUMMARY, key, locale as ReportLocale) ?? key;
}

export function statusLabel(value: string, locale: string): string {
  return pick(STATUS, value, locale as ReportLocale) ?? value;
}

export function roleLabel(value: string, locale: string): string {
  return pick(ROLES, value, locale as ReportLocale) ?? value;
}

export function appBrandName(locale: string): string {
  return locale === "bn" ? APP_NAME.bn : APP_NAME.en;
}

export function formatReportCurrency(
  amount: number,
  currency: string,
  locale: string,
  opts?: { suffix?: boolean }
): string {
  const loc = locale === "bn" ? "bn-BD" : "en-US";
  const hasDecimals = Math.round(amount * 100) % 100 !== 0;
  const formatted = amount.toLocaleString(loc, {
    minimumFractionDigits: hasDecimals ? 2 : 0,
    maximumFractionDigits: hasDecimals ? 2 : 0,
  });

  if (opts?.suffix) return `${formatted} ${currency}`;
  const symbols: Record<string, string> = { BDT: "৳", USD: "$", EUR: "€" };
  const sym = symbols[currency] ?? `${currency} `;
  return locale === "bn" && currency === "BDT" ? `${sym} ${formatted}` : `${sym}${formatted}`;
}

export function summaryKeyFromLabel(label: string): string {
  return SUMMARY_LABEL_TO_KEY[label] ?? label;
}
