const EN: Record<string, string> = {
  summary: "Summary",
  member: "Member",
  deposit: "Deposit",
  mealCost: "Meal Cost",
  balance: "Balance",
  due: "Due",
  advance: "Advance",
  generatedBy: "Generated By",
  generatedAt: "Generated At",
  generatedOn: "Generated On",
  reportType: "Report Type",
  noData: "No data for this period.",
  footer: "MessFlow Pro — Generated Automatically",
  page: "Page",
  of: "of",
  reportId: "Report ID",
};

const BN: Record<string, string> = {
  summary: "সারাংশ",
  member: "সদস্য",
  deposit: "জমা",
  mealCost: "মিল খরচ",
  balance: "ব্যালেন্স",
  due: "বকেয়া",
  advance: "অগ্রিম",
  generatedBy: "রিপোর্ট প্রস্তুতকারী",
  generatedAt: "প্রস্তুতের সময়",
  generatedOn: "প্রস্তুতের তারিখ",
  reportType: "রিপোর্টের ধরন",
  noData: "এই সময়ের জন্য কোনো ডেটা নেই।",
  footer: "MessFlow Pro — স্বয়ংক্রিয়ভাবে তৈরি",
  page: "পৃষ্ঠা",
  of: "এর",
  reportId: "রিপোর্ট আইডি",
};

const REPORT_TITLES: Record<string, { en: string; bn: string }> = {
  monthly: { en: "Monthly Settlement Report", bn: "মাসিক হিসাব রিপোর্ট" },
  member: { en: "Member Report", bn: "সদস্য রিপোর্ট" },
  meal: { en: "Meal Report", bn: "মিল রিপোর্ট" },
  expense: { en: "Expense Report", bn: "খরচ রিপোর্ট" },
  deposit: { en: "Deposit Report", bn: "জমা রিপোর্ট" },
  utility: { en: "Utility Bill Report", bn: "ইউটিলিটি বিল রিপোর্ট" },
  rent: { en: "Rent Report", bn: "ভাড়া রিপোর্ট" },
  balance_sheet: { en: "Balance Report", bn: "ব্যালেন্স রিপোর্ট" },
  due: { en: "Due Report", bn: "বকেয়া রিপোর্ট" },
  bazaar: { en: "Bazaar Report", bn: "বাজার রিপোর্ট" },
  transaction: { en: "Transaction Report", bn: "লেনদেন রিপোর্ট" },
  yearly: { en: "Annual Financial Report", bn: "বার্ষিক আর্থিক রিপোর্ট" },
  shared_expense: { en: "Shared Expense Report", bn: "ভাগীয় খরচ রিপোর্ট" },
  bill_settlement: { en: "Bill Settlement Report", bn: "বিল নিষ্পত্তি রিপোর্ট" },
};

export function reportLabel(key: string, locale: string): string {
  const dict = locale === "bn" ? BN : EN;
  return dict[key] ?? key;
}

export function reportTitle(type: string, locale: string): string {
  const t = REPORT_TITLES[type];
  if (!t) return type;
  return locale === "bn" ? t.bn : t.en;
}

export function formatReportCurrency(amount: number, currency: string, locale: string): string {
  const symbols: Record<string, string> = { BDT: "৳", USD: "$", EUR: "€" };
  const sym = symbols[currency] ?? "৳";
  const hasDecimals = Math.round(amount * 100) % 100 !== 0;
  const formatted = amount.toLocaleString(locale === "bn" ? "bn-BD" : "en-US", {
    minimumFractionDigits: hasDecimals ? 2 : 0,
    maximumFractionDigits: hasDecimals ? 2 : 0,
  });
  return `${sym}${formatted}`;
}
