export const PLAN_FEATURES = {
  MEAL_MANAGEMENT: "meal_management",
  DEPOSIT_MANAGEMENT: "deposit_management",
  EXPENSE_MANAGEMENT: "expense_management",
  BAZAAR_MANAGEMENT: "bazaar_management",
  UTILITY_BILLS: "utility_bills",
  PDF_REPORTS: "pdf_reports",
  EXCEL_REPORTS: "excel_reports",
  CSV_EXPORT: "csv_export",
  ANALYTICS: "analytics",
  AI_ANALYTICS: "ai_analytics",
  BRANCH_MANAGEMENT: "branch_management",
  ROOM_MANAGEMENT: "room_management",
  BED_MANAGEMENT: "bed_management",
  VISITOR_MANAGEMENT: "visitor_management",
  TASK_MANAGEMENT: "task_management",
  INVENTORY: "inventory",
  AUDIT_LOGS: "audit_logs",
  ADVANCED_REPORTS: "advanced_reports",
  CUSTOM_BRANDING: "custom_branding",
  API_ACCESS: "api_access",
  WEBHOOKS: "webhooks",
  PRIORITY_SUPPORT: "priority_support",
  WHITE_LABEL: "white_label",
  MULTI_BRANCH: "multi_branch",
  ADVANCED_ANALYTICS: "advanced_analytics",
  UNLIMITED_MEMBERS: "unlimited_members",
  UNLIMITED_REPORTS: "unlimited_reports",
  MEAL_TRACKING: "meal_tracking",
  EXPENSE_TRACKING: "expense_tracking",
  DEPOSIT_TRACKING: "deposit_tracking",
  MONTHLY_REPORT: "monthly_report",
  NOTICE_BOARD: "notice_board",
  EMAIL_NOTIFICATIONS: "email_notifications",
} as const;

export type PlanFeatureKey = (typeof PLAN_FEATURES)[keyof typeof PLAN_FEATURES];

export const PLAN_LIMIT_KEYS = [
  "members",
  "branches",
  "storage_mb",
  "reports",
  "pdf_exports",
  "excel_exports",
  "csv_exports",
  "monthly_transactions",
  "api_requests",
  "bazaar_entries",
  "expenses",
  "bills",
  "notices",
  "tasks",
] as const;

export type PlanLimitKey = (typeof PLAN_LIMIT_KEYS)[number];

export const LEGACY_FEATURE_MAP: Record<string, PlanFeatureKey> = {
  meal_management: "meal_management",
  deposit_management: "deposit_management",
  expense_management: "expense_management",
  bazaar_management: "bazaar_management",
  utility_bills: "utility_bills",
  pdf_export: "pdf_reports",
  excel_export: "excel_reports",
  csv_export: "csv_export",
  analytics: "analytics",
  ai_analytics: "ai_analytics",
  branch_management: "branch_management",
  room_management: "room_management",
  bed_management: "bed_management",
  visitor_management: "visitor_management",
  task_management: "task_management",
  inventory: "inventory",
  advanced_reports: "advanced_reports",
  audit_logs: "audit_logs",
  custom_branding: "custom_branding",
  api_access: "api_access",
  webhooks: "webhooks",
  custom_integrations: "white_label",
  basic_meal_tracking: "meal_tracking",
  expense_tracking: "expense_tracking",
  deposit_tracking: "deposit_tracking",
  monthly_report: "monthly_report",
  notice_board: "notice_board",
  email_notifications: "email_notifications",
  sms_notifications: "email_notifications",
  dedicated_support: "priority_support",
};